### PR TITLE
Scan more than 10,000 transactions

### PR DESCRIPTION
**Pull request by DesWurstes**
And python3!

Blockchain.com had a limit of 10,000 transactions, so I changed the URL.

### CODE REVIEW

**Comment by balasid1404** [comment]
it says index out of range can you post the fixed script please

**Comment by DesWurstes** [comment]
@balasid1404 Does it work now?

**Comment by balasid1404** [comment]
Sir I will check it did you remove the index limit?

**Comment by DesWurstes** [comment]
Whoops sorry I noticed I just fixed another bug. I'll report once again once I fix the bug you found

**Comment by DesWurstes** [comment]
I fixed it, it should work now

**Comment by balasid1404** [comment]
Sir I used it it work perfect now but how can I paste bulk addresses and
scan them automatically? I am completely beginner for python can you help
me?

**Comment by DesWurstes** [comment]
I updated it once again. You can now use it like:

```bash
for param in 1MsHWS1BnwMc3tLE8G35UXsS58fKipzB7a 1CijKR7rDvJJBJfSPyUYrWC8kAsQLy2B2e; do python3 /rscan.py $param; done >/dev/null
```

It will print only if matches are found.

**Comment by balasid1404** [comment]
I can't understand what you are saying can you just add all the command and enable it to just copy paste the address?? I am just starting to understand your program it will be a great help

**Comment by DesWurstes** [comment]
You can download the newer `rscan.py` and use Terminal commands to run it with different addresses.
The Terminal command is:

```
for param in add addressed here; do python3 /rscan.py $param; done >/dev/null
```

where `add addressed here` are space separated addresses.

**Comment by balasid1404** [comment]
But I hope if we can add the addresses in text file and then run a batch
file to scan whole text file it will be easy can you please make it?

**Comment by DesWurstes** [comment]
You can enter addresses in a file named `a.txt` separated by a space or newline and call the script as follows (paste into terminal):

```bash
for param in `cat a.txt`; do python3 rscan.py $param; done >/dev/null
```

**Comment by balasid1404** [comment]
I did it but it says param is not defined and by terminal you mean cmd or
linux terminal and please say step by step where to open like that I am a
complete noob

**Comment by DesWurstes** [comment]
OK

- Linux Terminal (or type `bash` and enter before running any other commands below)

`a.txt` in the current directory (Or use `cd $HOME/Desktop` for example if the file is on your desktop) should be like:

```
1ABC..
1DNS..
```

(Line separated addresses)

`rscan.py` should be in the same directory too. Then paste this:
```
for param in `cat a.txt`; do python3 rscan.py $param; done >/dev/null
```

**Comment by balasid1404** [comment]
Can't I do this in windows?

**Comment by DesWurstes** [comment]
Okay, for Window just use my updated script: https://gist.github.com/DesWurstes/8bfeac78dad31011dddd511cb0c1526d with the standard python3 command

In the same directory as the updated script, the addresses must be in `addr.txt`

**Comment by balasid1404** [comment]
Thanks a lot sir I admire your work a lot!! I hope I can become a
programmer like you. I am doing vulnerability analysis with your code
thanks a lot for this

**Comment by DesWurstes** [comment]
You're welcome, happy to help, let me know if something goes wrong.

**Comment by balasid1404** [comment]
It works perfectly but how can I store the output of each address as
different text automatically?

**Comment by balasid1404** [comment]
I mean as text file

**Comment by DesWurstes** [comment]
Call it as
```bash
python3 rscan.py 2>out.txt
```
it will print only the addresses and found matches to `out.txt` while printing progress to the command prompt normally so you can see that it's working.

**Comment by balasid1404** [comment]
sir now it says again index list out of range and also the process is very slow now

**Comment by DesWurstes** [comment]
I fixed the index problem, updated at here: https://gist.github.com/DesWurstes/8bfeac78dad31011dddd511cb0c1526d

Is it still slow? I can't understand why it's so.

**Comment by balasid1404** [comment]
Now it works perfectly sir no index error or slow issue if any issue
persists I will forward it to you

**Comment by DesWurstes** [comment]
Excellent, thank you for telling me that it worked for you!

**Comment by kpot87** [comment]
@DesWurstes Hi? i have a question when i load addr.txt its freez on first addres. what can be issue? thank you

**Comment by Luci-hub** [comment]
Hi,  when i scan an address i get this kind of results at out.txt 
Screenshot_2
it gives non re-used results at out.txt as well.  

> Call it as
> 
> ```shell
> python3 rscan.py 2>out.txt
> ```
> 
> it will print only the addresses and found matches to `out.txt` while printing progress to the command prompt normally so you can see that it's working.

**Comment by DesWurstes** [comment]
@Luci-hub Where's the problem so?

**Comment by Luci-hub** [comment]
> @Luci-hub Where's the problem so?

It spams the r values and shows empty lines while saying that there are re-used r values

**Comment by DesWurstes** [comment]
The next lines after `Reused R-value` show the r value.

**Comment by Luci-hub** [comment]
The problem is this, it shows empty lines without giving re-used r values. And it spams it over and over again.
Screenshot-3
Can you add something that can show txid as well?

**Comment by DesWurstes** [comment]
Sure, there is a newer version at https://gist.github.com/DesWurstes/937de5ce335fe255eccc23b2abded49e

It's used the same way.

**Comment by Luci-hub** [comment]
Screenshot_13
I dont understand this much however it seems like the problem with not showing re-used r value is not gone in this version again. Thank you for this new update. 

> Sure, there is a newer version at https://gist.github.com/DesWurstes/937de5ce335fe255eccc23b2abded49e
> 
> It's used the same way.

**Comment by DesWurstes** [comment]
~~Hello, it's now showing you the TXIDs, what are you trying to achieve?~~

Ah I see the issue now, this code doesn't work all the time... The address is probably safe, Let me see what I can do now to fix the code.

**Comment by DesWurstes** [comment]
Hello, I can't fix those false positives, it's too much work. I don't think there are any vulnerable addresses left anyway.

**Comment by Luci-hub** [comment]
thank you for your help

**Comment by DesWurstes** [comment]
You're welcome... as I said I can't help because my code doesn't work on even my computer.

**Comment by Luci-hub** [comment]
I see, thank you again. If you again decide to check the codes please let me know .

**Comment by Ango87** [comment]
@DesWurstes  sir please how i can contact you x help me

**Comment by Ango87** [comment]
I got an error
blink@localhost:/storage/emulated/0/Download/rng-scanner$ python3 rscan.py
WELCOME TO R-scan v0.1.4!                         ADDRESS-R-SCAN:
type address:  15Fho2TVSG9Q8Vr1Rg9sUH29x1oBkSFcgm 
https://api-r.bitcoinchain.com/v1/address/txs/15Fho2TVSG9Q8Vr1Rg9sUH29x1oBkSFcgm
Traceback (most recent call last):
  File "/sdcard/Download/rng-scanner/rscan.py", line 49, in <module>
    countdata = json.loads(request_source(countaddr))
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by RiaanGroen** [comment]
I get the same error.

", line 44, in main
    countdata = json.loads(request_source(countaddr))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Pull request closed without merging**
